### ISSUE TITLE
Plan January 2022

### ISSUE THREAD

**Issue by nardiyansah** [nardiyansah/Journey-to-Backend#4]
**Deadline**
31 January 2022

**Descriptions**
Learn about the **internet**

**Task(s)**
- [ ] read 1 article about **How does the internet work** and create summary in readme.md & create anki cards
- [ ] read 1 article about **What is HTTP** and create summary in readme.md & create anki cards
- [ ] read 1 article about **Browsers and how they work** and create summary in readme.md & create anki cards
- [ ] read 1 article about **DNS and how it works** and create summary in readme.md & create anki cards
- [ ] read 1 article about **What is Domain Name** and create summary in readme.md & create anki cards
- [ ] read 1 article about **What is hosting** and create summary in readme.md & create anki cards

**Additional context**
